/**
 * Issue #73: Cron job fires immediately on restart
 *
 * Reproduces the exact scenario reported by @arthurvanl:
 * 1. Cron `* * * * *` fires, job pushed with preventOverlap
 * 2. Worker pulls job (active state)
 * 3. App killed (^C) during job execution
 * 4. Server restarts → job fires "right away"
 *
 * Root cause: On restart, `recover()` finds the active cron job in SQLite
 * and re-queues it (stall recovery). The worker picks it up immediately.
 * Neither `skipMissedOnRestart` nor `preventOverlap` prevent this because
 * they only affect the cron scheduler, not the recovery mechanism.
 *
 * Fix: During recovery, skip jobs with uniqueKey starting with 'cron:'
 * (auto-generated by preventOverlap). These jobs are discarded and the
 * cron scheduler will push a new one at the next scheduled time.
 *
 * @see https://github.com/egeominotti/bunqueue/issues/73
 */

import { describe, test, expect, afterEach } from 'bun:test';
import { tmpdir } from 'os';
import { join } from 'path';
import { unlinkSync, existsSync } from 'fs';
import { sleep } from 'bun';
import { QueueManager } from '../src/application/queueManager';

const TEST_DB_PATH = join(tmpdir(), `bunqueue-issue73-restart-${Date.now()}.db`);

function cleanup() {
  for (const suffix of ['', '-wal', '-shm']) {
    const p = TEST_DB_PATH + suffix;
    if (existsSync(p)) {
      try { unlinkSync(p); } catch {}
    }
  }
}

/** Flush the write buffer so all jobs are persisted to SQLite */
function flushStorage(manager: QueueManager): void {
  const storage = (manager as any).storage;
  if (storage) storage.flushWriteBuffer();
}

describe('Issue #73: cron job fires immediately on restart', () => {
  afterEach(cleanup);

  test('recovery discards active cron jobs with preventOverlap uniqueKey', async () => {
    // === PHASE 1: First server instance ===
    const manager1 = new QueueManager({ dataPath: TEST_DB_PATH });
    const queueName = 'testing';

    // Add cron with preventOverlap (default: true)
    manager1.addCron({
      name: 'start-new-test-job',
      queue: queueName,
      data: { type: 'test' },
      schedule: '* * * * *',
    });

    // Force the cron to fire
    const scheduler1 = (manager1 as any).cronScheduler;
    const cronEntry1 = scheduler1.cronJobs.get('start-new-test-job');
    cronEntry1.cron.nextRun = Date.now() - 1000;
    scheduler1.cronHeap.buildFrom(
      Array.from(scheduler1.cronJobs.values()).map((e: any) => ({
        cron: e.cron,
        generation: e.generation,
      }))
    );
    (scheduler1 as any).lastFiredAt.clear();
    await (scheduler1 as any).tick();

    // Flush write buffer so the job is persisted to SQLite
    flushStorage(manager1);

    // Worker pulls job → now active
    const job = await manager1.pull(queueName);
    expect(job).not.toBeNull();
    expect(job!.uniqueKey).toBe('cron:start-new-test-job');

    // Verify job is marked active in SQLite
    const activeJobs = (manager1 as any).storage.loadActiveJobs();
    expect(activeJobs.length).toBe(1);
    expect(activeJobs[0].uniqueKey).toBe('cron:start-new-test-job');

    // === SIMULATE CRASH ===
    manager1.shutdown();

    // === PHASE 2: Server restart ===
    const manager2 = new QueueManager({ dataPath: TEST_DB_PATH });

    // The cron job should have been discarded by recovery (not re-queued)
    const recovered = await manager2.pull(queueName);
    expect(recovered).toBeNull();

    // Queue should be empty
    const counts = manager2.getQueueJobCounts(queueName);
    expect(counts.waiting).toBe(0);
    expect(counts.active).toBe(0);

    manager2.shutdown();
  });

  test('recovery still re-queues normal jobs (no cron uniqueKey)', async () => {
    const manager1 = new QueueManager({ dataPath: TEST_DB_PATH });
    const queueName = 'normal-jobs';

    // Push a normal job (no cron uniqueKey)
    await manager1.push(queueName, { data: { type: 'payment' } });
    flushStorage(manager1);

    // Pull it (active)
    const job = await manager1.pull(queueName);
    expect(job).not.toBeNull();
    expect(job!.uniqueKey).toBeNull();

    // Crash
    manager1.shutdown();

    // Restart — normal job should be recovered
    const manager2 = new QueueManager({ dataPath: TEST_DB_PATH });
    const counts = manager2.getQueueJobCounts(queueName);

    // Job should be re-queued (delayed with backoff)
    expect(counts.waiting + (counts as any).delayed).toBeGreaterThanOrEqual(1);

    manager2.shutdown();
  });

  test('recovery still re-queues cron jobs WITHOUT preventOverlap', async () => {
    const manager1 = new QueueManager({ dataPath: TEST_DB_PATH });
    const queueName = 'cron-no-overlap';

    // Add cron WITHOUT preventOverlap
    manager1.addCron({
      name: 'no-overlap-cron',
      queue: queueName,
      data: { type: 'test' },
      schedule: '* * * * *',
      preventOverlap: false,
    });

    // Push a job manually (simulating cron fire without uniqueKey)
    await manager1.push(queueName, { data: { tick: 1 } });
    flushStorage(manager1);

    // Pull it (active)
    const job = await manager1.pull(queueName);
    expect(job).not.toBeNull();
    expect(job!.uniqueKey).toBeNull();

    // Crash
    manager1.shutdown();

    // Restart — job should be recovered (no 'cron:' uniqueKey to skip)
    const manager2 = new QueueManager({ dataPath: TEST_DB_PATH });
    const counts = manager2.getQueueJobCounts(queueName);
    expect(counts.waiting + (counts as any).delayed).toBeGreaterThanOrEqual(1);

    manager2.shutdown();
  });

  test('after recovery discard, cron fires normally at next schedule', async () => {
    const manager1 = new QueueManager({ dataPath: TEST_DB_PATH });
    const queueName = 'cron-after-discard';

    manager1.addCron({
      name: 'discard-then-fire',
      queue: queueName,
      data: { type: 'test' },
      schedule: '* * * * *',
    });

    // Force cron fire
    const scheduler1 = (manager1 as any).cronScheduler;
    const cronEntry1 = scheduler1.cronJobs.get('discard-then-fire');
    cronEntry1.cron.nextRun = Date.now() - 1000;
    scheduler1.cronHeap.buildFrom(
      Array.from(scheduler1.cronJobs.values()).map((e: any) => ({
        cron: e.cron,
        generation: e.generation,
      }))
    );
    (scheduler1 as any).lastFiredAt.clear();
    await (scheduler1 as any).tick();
    flushStorage(manager1);

    // Pull job (active)
    const job = await manager1.pull(queueName);
    expect(job).not.toBeNull();

    // Crash
    manager1.shutdown();

    // Restart — discarded cron job, but cron scheduler loaded
    const manager2 = new QueueManager({ dataPath: TEST_DB_PATH });

    // No recovered job
    expect(await manager2.pull(queueName)).toBeNull();

    // The cron is loaded and can fire again
    const scheduler2 = (manager2 as any).cronScheduler;
    const cronEntry2 = scheduler2.cronJobs.get('discard-then-fire');
    expect(cronEntry2).toBeDefined();

    // Force cron to fire on new instance
    cronEntry2.cron.nextRun = Date.now() - 1000;
    scheduler2.cronHeap.buildFrom(
      Array.from(scheduler2.cronJobs.values()).map((e: any) => ({
        cron: e.cron,
        generation: e.generation,
      }))
    );
    (scheduler2 as any).lastFiredAt.clear();
    await (scheduler2 as any).tick();

    // New job should be pushed
    const counts = manager2.getQueueJobCounts(queueName);
    expect(counts.waiting).toBe(1);

    const newJob = await manager2.pull(queueName);
    expect(newJob).not.toBeNull();
    expect(newJob!.id).not.toBe(job!.id);

    manager2.shutdown();
  });
});
